@startuml
class limba {
engleza
romana
maghiara
}
class prima_pagina {
text selecteaza limba
lista selecteaza limba
sageata continua
}

 class pagina_de_logare {
text Bun venit(...)
creare cont
am deja cont
}
 class text_creare_cont {
platforma google
platforma facebook
casuta nume
casuta nume_utilizator
casuta judet
casuta localitate
casuta e-mail
casuta parola
casuta confirmare parola
trei butoane
}
note left of text_creare_cont : numele de utilizator trebuie sa fie unic, in caz contrar, aplicatia va sugera cateva optiuni



class judet {
lista_ordine_alfabetica
judet_Romania

}
class localitate {
lista_ordine_alfabetica
localitate_Romania
}
class e-mail {
sir_de_caractere_[utilizator]@[domeniu]

}
class parola {
parola
litera_mica
majuscula
simbol
cifra
minim_8_caractere
}
 class text_am_deja_cont{
e-mail
forma[utilizator]@[domeniul]
parola
}
note left: aplicatia verifica datele daca exista in baza de date

class pagina_de_pornire {
adresa
bara de cautare
magazine
oferte
iconita "creare lista de cumparaturi"
}

class adresa{
localizare coordonate gps de la utilizator
}
note right: utilizatorul trebuie sa porneasca functia "Locatie" din telefon pentru furnizarea coordonatelor GPS

class bara_de_cautare {
adresa magazinului
coordonatele GPS ale magazinelor
}

class magazine {
Kaufland
Lidl
Profi
Auchan
Carrefour
Penny
}

class oferte {}
class liste_de_cumparaturi_finalizate {
coordonatele magazinului de unde au fost achitionate produsele
pretul listei de cumparaturi
data achizitionarii
cantitatea produselor
chenar pentru confirmarea achitionarii
totalul listei de cumparaturi
}

class cos_de_cumparaturi {
lista care urmaza sa fie achizitionata din magazin
denumirea produsului
cantitatea produsului
chenar pentru confirmarea achitionarii
}


@enduml