@startuml

class dropdownlist_limba {
optiune_limba
afiseaza_optiune_limba()
}

class prima_pagina {
text_selecteaza_limba
lista_selecteaza_limba
sageata_"continua"
afiseaza_text_selecteaza_limba()
}

prima_pagina -- dropdownlist_limba


 class pagina_de_logare {
text_Bun_venit(...)
creare_cont
am_deja_cont
afisare_text_Bun_venit(...)
}

pagina_de_logare -- text_am_deja_cont
pagina_de_logare -- text_creare_cont

 class text_creare_cont {
buton_google
buton_facebook
chenar_nume
chenar_nume_utilizator
chenar_judet
chenar_localitate
chenar_e-mail
chenar_parola
chenar_confirmare parola
trei_butoane
verifica_nume_de_utilizator
afiseaza_buton_google()
afiseaza_buton_facebook()
afiseaza_chenar_nume()
afiseaza_chenar_nume_utilizator()
afiseaza_chenar_judet()
afiseaza_chenar_localitate()
afiseaza_chenar_e-mail()
afiseaza_chenar_parola()
afiseaza_chenar_confirmare_parola()
afiseaza_cele_trei_butone_de_bifat()

}
class nume_de_utilizator {
label
nume_de_utilizator_unic
afiseaza_nume_de_utilizator ()
verifica_nume_de_utilizator_daca_exsita_in_baza_de_date
sugereaza_nume_de_utilizator_care_nu_a_mai_fost_folosit

}

class judet {
label
afiseaza_text_selecteza_judet()
afiseaza_dropdownlist_in_ordine_alfabetica_judet()
}

class localitate {
label
afiseaza_text_selecteaza_localitate()
afiseaza_dropdownlist_in_ordine_alfabetica_localitate()
}

class E_mail {
label
verifica_sir_de_caractere_[utilizator]@[domeniu]

}

class parola {
label
parola
litera mica
majuscula
simbol
cifra
minim_8_caractere
verica_sir_de_caractere()
verifica_minim_8_caractere()
}

text_creare_cont -- judet
text_creare_cont -- localitate
text_creare_cont -- parola
text_creare_cont -- E_mail

 class text_am_deja_cont{
label_e-mail
format_[utilizator]@[domeniul]
label_parola
verifica_adresa_de_e-mail()
verifica_parola()
verifica_cont_existent()

}

text_am_deja_cont -- E_mail

class pagina_de_pornire {
adresa
bara_de_cautare
magazine
oferte
iconita_"creare_lista_de_cumparaturi"
afiseaza_adresa()
afiseaza_bara_de_cautare()
afiseaza_magazine()
afiseaza_oferte()
afiseaza_iconita_"creare_lista_de_cumparaturi"()
}

class adresa{
localizare_coordonate_gps_de_la_utilizator
obtine_coordonate_GPS_de_la_utilizator_prin_functia_"Locatie"()
}


class bara_de_cautare {
adresa_magazinului
coordonatele_GPS_ale_magazinelor
afiseaza_bara_de_cautare ()
obtine_coordonatele_magazinelor ()
afiseaza_bara_de_cautare ()

}

class magazine {
nume_magazin
afiseaza_sir_de_caractere_magazine()
}

class oferte {
nume_magazin
afiseaza_sirul_de_caractere_pentru_magazin()
termenul_ofertei
afiseaza_termenul_ofertei()
pretul_produsului
afiseaza_pretul_produsului()
}

class liste_de_cumparaturi_finalizate {
coordonatele_magazinului_de_unde_au_fost_achitionate_produsele
preia_coordonatele_magazinului_de_unde_au_fost_achizitionate_produsele()
afiseaza_numele_magazinului()
pretul_listei_de_cumparaturi
afiseaza_pretul_listei_de_cumparaturi()

}

class lista_de_cumparaturi_finalizata {
data_achizitionarii
afiseaza_data_achizitionarii()
cantitatea_produselor
afiseaza_cantitatea_produselor()
chenar_pentru_confirmarea_achitionarii_unui_produs
afiseaza_chenar_pentru_confirmare_achizitionarii_unui_produs()
totalul_listei_de_cumparaturi
afiseaza_totalul_listei_de_cumparaturi()

}

liste_de_cumparaturi_finalizate -- lista_de_cumparaturi_finalizata

class cos_de_cumparaturi {
lista care urmaza sa fie achizitionata din magazin
denumirea produsului
cantitatea produsului
chenar pentru confirmarea achitionarii
}

class creare_lista_de_cumparaturi {


}
pagina_de_pornire -- adresa
pagina_de_pornire -- bara_de_cautare
pagina_de_pornire -- magazine
pagina_de_pornire -- oferte
pagina_de_pornire -- liste_de_cumparaturi_finalizate
pagina_de_pornire -- cos_de_cumparaturi
pagina_de_pornire -- creare_lista_de_cumparaturi




@enduml